### ISSUE TITLE
MVP: full stack ROADMAP

### ISSUE THREAD

**Issue by giuseppeambrosio97** [giuseppeambrosio97/detr-full-stack#1]
## TODOs

- [x] #2
- [x] #4
- [x] #6
- [x] extract simple services to use in the api
- [x] #8
- [x] frontend implement endpoints api
- [x] frontend implement ui
- [x] #9
- [x] #10
- [x] docker-compose.yml for frontend and backend
- [x] #13
